# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='IMAGE', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/attachment/')),
                ('video', models.URLField(blank=True, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('extra_properties', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'verbose_name_plural': 'Attachments',
                'verbose_name': 'Attachment',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='STANDARD', max_length=16)),
                ('markup_language', models.CharField(choices=[('HTML', 'HTML'), ('MD', 'Markdown'), ('RST', 'reStructuredText')], default='HTML', max_length=50)),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/post/')),
                ('featured_video', models.URLField(blank=True, null=True)),
                ('featured_audio', models.URLField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='blog.Attachment')),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
