# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_on'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
